<h1>Labels and SQL Expressions</h1>

<p>Labels are generated by using SQL expressions. The &laquo;SQL expression&raquo; is added to WHERE clause of view feed query. You can match on ttrss_entries table fields and even use subselect to query additional information. This 	functionality is considered to be advanced and requires some understanding of SQL.</p>
	
<h2>Examples</h2>

<p>Match all unread articles:</p>

<pre>unread = true</pre>

<p>Matches all articles which mention Linux in the title:</p>

<pre>ttrss_entries.title like '%Linux%'</pre>

<p>See the database schema included in the distribution package for gruesome
details.</p>

