*.php usr/share/tt-rss/www/
*.css usr/share/tt-rss/www/
js usr/share/tt-rss/www/
include usr/share/tt-rss/www/
*.xsl usr/share/tt-rss/www/
api	usr/share/tt-rss/www
help  usr/share/tt-rss/www/
images usr/share/tt-rss/www/
lib usr/share/tt-rss/www/
locale usr/share/tt-rss/www/
mobile usr/share/tt-rss/www/
modules usr/share/tt-rss/www/
templates usr/share/tt-rss/www/
themes usr/share/tt-rss/www/
utils usr/share/tt-rss/www/

